[package]
name = "idle-worker"
version = "0.0.1"
authors = ["red <red.avtovo@gmail.com>"]
edition = "2018"

[dependencies]
# Config
dotenv = "0.15.0"

autopilot = "0.4.0"
rand = "0.7.3"
lerp = "0.2.0"